name: CI Build and Test

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build-ubuntu-gcc:
    name: Ubuntu with GCC
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool \
                                pkg-config m4 libgmp-dev libgmpxx4ldbl
    
    - name: Configure
      run: |
        autoreconf -vif
        mkdir -p build-gcc
        cd build-gcc
        ../configure CC=gcc CXX=g++
    
    - name: Build
      run: |
        cd build-gcc
        make -j$(nproc)
    
    - name: Test
      run: |
        cd build-gcc
        make check
    
    - name: Display test results
      if: always()
      run: |
        cd build-gcc/tests
        if [ -f test-suite.log ]; then
          echo "=== Test Suite Summary ==="
          tail -100 test-suite.log
        fi

  build-ubuntu-clang:
    name: Ubuntu with Clang + libc++
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool \
                                pkg-config m4 libgmp-dev libgmpxx4ldbl \
                                clang libc++-dev libc++abi-dev
    
    - name: Configure
      run: |
        autoreconf -vif
        mkdir -p build-clang
        cd build-clang
        ../configure CC=clang CXX=clang++ \
                     CXXFLAGS="-stdlib=libc++ -D__GIVARO_GMP_NO_CXX" \
                     LDFLAGS="-stdlib=libc++"
    
    - name: Build
      run: |
        cd build-clang
        make -j$(nproc)
    
    - name: Test
      run: |
        cd build-clang
        make check
    
    - name: Display test results
      if: always()
      run: |
        cd build-clang/tests
        if [ -f test-suite.log ]; then
          echo "=== Test Suite Summary ==="
          tail -100 test-suite.log
        fi

  build-macos-clang:
    name: macOS with Clang
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        brew install autoconf automake libtool pkg-config gmp
    
    - name: Configure
      run: |
        autoreconf -vif
        mkdir -p build-macos
        cd build-macos
        ../configure CC=clang CXX=clang++ \
                     CXXFLAGS="-stdlib=libc++ -D__GIVARO_GMP_NO_CXX" \
                     LDFLAGS="-stdlib=libc++"
    
    - name: Build
      run: |
        cd build-macos
        make -j$(sysctl -n hw.ncpu)
    
    - name: Test
      run: |
        cd build-macos
        make check
    
    - name: Display test results
      if: always()
      run: |
        cd build-macos/tests
        if [ -f test-suite.log ]; then
          echo "=== Test Suite Summary ==="
          tail -100 test-suite.log
        fi
